Intake Subsystem
Frc5572/FRC2024 pull request #10
Opened 2024-01-26 16:56 UTC by wilsonwatson

2024-01-26 16:58 UTC, wilsonwatson commented on src/main/java/frc/robot/subsystems/intake/Intake.java
> +    public Command runIntakeMotor = Commands.startEnd(() -> {
A command can only be run once, so reusing this will cause the program to crash. We should instead generate this in a function (as a factory method).

2024-01-27 20:17 UTC, legoguy1000 requested changes

2024-01-27 20:17 UTC, legoguy1000 commented on src/main/java/frc/robot/Constants.java
> +
put with other motors

2024-01-27 20:48 UTC, legoguy1000 approved these changes

2024-01-27 20:48 UTC, merged