Shooter subsystem
Frc5572/FRC2024 pull request #11
Opened 2024-01-26 16:57 UTC by wilsonwatson

2024-01-26 17:05 UTC, wilsonwatson commented on src/main/java/frc/robot/subsystems/shooter/ShooterVortex.java
> +public class ShooterVortex implements ShooterIO {
This class is missing an implementation of `updateInputs`.

2024-01-27 17:26 UTC, legoguy1000 requested changes

2024-01-27 17:26 UTC, legoguy1000 commented on src/main/java/frc/robot/Constants.java
> +
remove extra lines

2024-01-27 17:26 UTC, legoguy1000 commented on src/main/java/frc/robot/Constants.java
> +        public static final int shooterBottomId = 0;
Move Motor CAN Ids into the Motors class above.  See whats currently in main

2024-01-27 17:26 UTC, legoguy1000 commented on src/main/java/frc/robot/subsystems/shooter/Shooter.java
> +    public void periodic() {
This should be an `@Override`

2024-01-27 17:26 UTC, legoguy1000 commented on src/main/java/frc/robot/subsystems/shooter/ShooterIO.java
> +    }
collapse to 1 line

2024-01-27 17:26 UTC, legoguy1000 commented on src/main/java/frc/robot/subsystems/shooter/ShooterIO.java
> +    }
collapse to 1 line

2024-01-27 17:26 UTC, legoguy1000 commented on src/main/java/frc/robot/subsystems/shooter/ShooterIO.java
> +    }
collapse to 1 line

2024-01-27 17:26 UTC, legoguy1000 commented on src/main/java/frc/robot/subsystems/shooter/ShooterIO.java
> +    }
remove extra blank lines

2024-01-27 17:26 UTC, legoguy1000 commented on src/main/java/frc/robot/subsystems/shooter/ShooterVortex.java
> +        inputs.bottomshooterVelocityRotPerSecond = bottomEncoder.getPosition();
`.getPosition()` gives you the position not velocity.

2024-01-27 20:15 UTC, legoguy1000 approved these changes

2024-01-27 20:15 UTC, legoguy1000 requested changes
Add commands

2024-01-27 20:18 UTC, legoguy1000 requested changes
You need to add subsystem to Robot Container

2024-01-27 20:49 UTC, legoguy1000 commented on src/main/java/frc/robot/RobotContainer.java
> +    private Shooter shooter;
Look at Robot Container COntrstuctor!!!!!!

2024-01-27 20:54 UTC, legoguy1000 commented on src/main/java/frc/robot/subsystems/shooter/Shooter.java
> +    }
This doesn't make sense.. You're not using the PID controller at all here. Also the PID doesn't need to be running all the time. Only when we want to shoot, ie when I start the command.

2024-01-27 21:30 UTC, legoguy1000 approved these changes

2024-01-27 21:32 UTC, merged