Climber Subsytem
Frc5572/FRC2024 pull request #26
Opened 2024-01-31 03:18 UTC by owenflatman

Created subsystem, with command, io, and added setpoints for elevator and wrist.

2024-01-31 03:27 UTC, legoguy1000 requested changes

2024-01-31 03:27 UTC, legoguy1000 commented on src/main/java/frc/robot/subsystems/climber/ClimberNEO.java
> +        rightMotor.follow(leftMotor);
Probably need to invert one of the motors too.

https://codedocs.revrobotics.com/java/com/revrobotics/cansparkbase#follow(com.revrobotics.CANSparkBase,boolean)

2024-01-31 03:27 UTC, legoguy1000 commented on src/main/java/frc/robot/subsystems/climber/ClimberNEO.java
> +
`.get()` gives the power from -1 to 1 not the voltage. I presume u want `getBusVoltage()`

2024-01-31 03:27 UTC, legoguy1000 commented on src/main/java/frc/robot/subsystems/climber/ClimberNEO.java
> +    public void updateInputs(ClimberInputs inputs) {
Same as above

2024-01-31 03:27 UTC, legoguy1000 commented on src/main/java/frc/robot/subsystems/climber/Climber.java
> +    }
Ok, let's add some logic to get encoder value

2024-01-31 03:32 UTC, owenflatman commented on src/main/java/frc/robot/subsystems/climber/Climber.java
> +    }
like what we did in elevatorwrist subsystem?

2024-01-31 03:35 UTC, legoguy1000 commented on src/main/java/frc/robot/subsystems/climber/Climber.java
> +    }
I'd have to look but my instincts say yes

2024-01-31 03:36 UTC, owenflatman commented on src/main/java/frc/robot/subsystems/climber/Climber.java
> +    }
Im pretty sure we are missing that on shooter and intake, are you wanting me to add that as well

2024-01-31 03:37 UTC, owenflatman commented on src/main/java/frc/robot/subsystems/climber/Climber.java
> +    }
and why is climber not profiled pid?

2024-01-31 04:44 UTC, legoguy1000 requested changes

2024-01-31 04:44 UTC, legoguy1000 commented on src/main/java/frc/robot/subsystems/climber/Climber.java
> +    PIDController climberPID = new PIDController(Constants.ClimberConstants.CLIMBER_KP,
I didn't think of it earlier but you'll need to make a controller for each motor.

2024-01-31 04:44 UTC, legoguy1000 commented on src/main/java/frc/robot/subsystems/climber/Climber.java
> +        double climberFeedForwardValue = climberFeedforward.calculate(0, 0, climberPID.getPeriod());
This will need to be separated for each motor and moved out of periodic. It will only be used once we want to actually climb, or in the command.

2024-01-31 04:47 UTC, owenflatman commented on src/main/java/frc/robot/subsystems/climber/Climber.java
> +        double climberFeedForwardValue = climberFeedforward.calculate(0, 0, climberPID.getPeriod());
so put where?

2024-01-31 12:51 UTC, legoguy1000 submitted a review, later dismissed

2024-01-31 12:51 UTC, legoguy1000 commented on src/main/java/frc/robot/Constants.java
> +        public static final double RIGHT_CLIMBER_KV = 0;
Shouldn't need different pid variables. They can use the same variables cause we want them to move at the same rate

2024-01-31 12:51 UTC, legoguy1000 commented on src/main/java/frc/robot/subsystems/climber/Climber.java
> +        Constants.ClimberConstants.RIGHT_CLIMBER_KV);
Feed forward also shouldn't need separate ones.

2024-01-31 12:51 UTC, legoguy1000 commented on src/main/java/frc/robot/subsystems/climber/Climber.java
> +        return Commands.runOnce(() -> {
It won't be just a Run once. You can use that to set the goal and then u need a Run command to continuously calculate the voltage with PID and control the motor until we reach the end

2024-01-31 23:59 UTC, wilsonwatson commented on src/main/java/frc/robot/Constants.java
> -            public static final Rotation2d MAX_ANGLE_DOWN_EXTENDED = Rotation2d.fromDegrees(-15);
Why were these removed?

2024-02-01 00:02 UTC, wilsonwatson commented on src/main/java/frc/robot/subsystems/climber/Climber.java
> +    }
do we not need to call `setClimberVoltage` here?

2024-02-01 00:22 UTC, wilsonwatson approved these changes

2024-02-01 00:23 UTC, merged