LEDs subsytem
Frc5572/FRC2024 pull request #39
Opened 2024-02-03 17:36 UTC by owenflatman

Created LEDs without IO. Then made commands
close #34

2024-02-03 23:17 UTC, legoguy1000 requested changes

2024-02-03 23:17 UTC, legoguy1000 commented on src/main/java/frc/robot/subsystems/LEDs.java
> +    public LEDs(int length, int port) {
I don't need the arguments

2024-02-03 23:17 UTC, legoguy1000 commented on src/main/java/frc/robot/subsystems/LEDs.java
> +        addressableLED = new AddressableLED(port);
This can be outside the constructor where it's defined.

2024-02-15 16:56 UTC, wilsonwatson approved these changes
Looks like a kitchen sink, but otherwise is fine.

2024-02-26 13:42 UTC, legoguy1000 commented on src/main/java/frc/robot/subsystems/climber/Climber.java
> +        Logger.recordOutput("/Climber/Feedforward", climberFeedForwardValue);
IDK why this is here but shouldn't be changing things in CLimber in this PR.  probably a merge issue.

2024-02-26 13:44 UTC, legoguy1000 requested changes
Lets take a few min and figure out what LED functions/actions we actually want and then only merge in what we need. Not everything. If we're not going to use it, lets keep it out of the code for now since it just clutters things.

2024-02-26 13:44 UTC, legoguy1000 commented on src/main/java/frc/robot/subsystems/elevator_wrist/ElevatorWrist.java
> +        double wristFeedForwardValue = wristFeedForward.calculate(0, 0);
IDK why this is here but shouldn't be changing things in Elevator in this PR.  probably a merge issue.

2024-02-26 13:44 UTC, legoguy1000 commented on src/main/java/frc/robot/Constants.java
> +            public static final double WRIST_KV = 0.001;
Same as other comments

2024-02-26 13:44 UTC, legoguy1000 commented on src/main/java/frc/robot/RobotContainer.java
> +    private Climber climber;
same

2024-02-26 13:44 UTC, legoguy1000 commented on src/main/java/frc/robot/RobotContainer.java
> +import frc.robot.subsystems.elevator_wrist.ElevatorWrist;
same

2024-02-27 08:25 UTC, legoguy1000 commented
lets add a trigger to robot container that flashes the LEDs whenever we have a note

2024-02-27 20:08 UTC, legoguy1000 commented on src/main/java/frc/robot/RobotContainer.java
> +        new Trigger(() -> intake.getSensorStatus())
Here's what we did last year. https://github.com/Frc5572/FRC2023/blob/b01038bf4f19c6f16ed4cc5fe20e5728422f1238/src/main/java/frc/robot/RobotContainer.java#L203

2024-02-28 17:29 UTC, owenflatman commented on src/main/java/frc/robot/RobotContainer.java
> +        new Trigger(() -> intake.getSensorStatus())
What do you mean? Why does the current code not work?

2024-02-28 23:10 UTC, owenflatman commented on src/main/java/frc/robot/RobotContainer.java
> +        new Trigger(() -> intake.getSensorStatus())
Nvm I understand

2024-03-03 04:45 UTC, wilsonwatson commented
This PR has become stale. Minimal LEDs are included in #82.

2024-03-03 04:45 UTC, closed without merging