Create Driver ShuffleBoard
Frc5572/FRC2024 pull request #86
Opened 2024-03-03 22:34 UTC by legoguy1000

closes #81

2024-03-03 23:03 UTC, wilsonwatson requested changes

2024-03-03 23:03 UTC, wilsonwatson commented on src/main/java/frc/robot/subsystems/elevator_wrist/ElevatorWrist.java
> +        .withWidget(BuiltInWidgets.kDial).withProperties(Map.of("Min", 0, "Max", 360))
Min/Max should be something like (-180, 180). 0 is flat, so we do go negative during amp/trap scoring.

2024-03-04 00:16 UTC, legoguy1000 commented on src/main/java/frc/robot/subsystems/elevator_wrist/ElevatorWrist.java
> +        .withWidget(BuiltInWidgets.kDial).withProperties(Map.of("Min", 0, "Max", 360))
done

2024-03-04 00:44 UTC, legoguy1000 commented
Shuffle Board
<img width="1384" alt="image" src="https://github.com/Frc5572/FRC2024/assets/13125104/d263fe8c-1d43-492e-9e3d-26bd7410fc77">
Elastic Dashboard (https://github.com/Gold872/elastic-dashboard)
<img width="1500" alt="image" src="https://github.com/Frc5572/FRC2024/assets/13125104/cb4e4d05-a0e7-4774-a26c-68cc24548414">

2024-03-04 00:46 UTC, owenflatman submitted a review, later dismissed

2024-03-04 02:28 UTC, legoguy1000 commented
<img width="1500" alt="image" src="https://github.com/Frc5572/FRC2024/assets/13125104/f19a4c23-47bc-4b87-ad88-e52835abfd93">

2024-03-04 02:29 UTC, legoguy1000 commented
Elastic dashboard configured via API. Have Note wil actually flash between green and blue like LEDs when we have a note

2024-03-04 02:57 UTC, owenflatman approved these changes

2024-03-04 02:57 UTC, merged